table Table
	lineageTag: cb2580b7-db63-444a-b343-87a1d7c6ba78

	column BU
		dataType: int64
		formatString: 0
		lineageTag: 44501de7-a581-480e-9c01-d2e39eb9fc60
		summarizeBy: sum
		sourceColumn: BU

		annotation SummarizationSetBy = Automatic

	column Disposables
		dataType: string
		lineageTag: ba4592c0-a812-43f7-bcef-21519e2fc831
		summarizeBy: none
		sourceColumn: Disposables

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("XY7BCoJAEIZfZfHsJYywo6lEsIKheREP2zq0A5sbu2o9fktQjR7/b75/Zto22EdRFIRBPdmrYbnGEYIu/OCNxzlPk2/+a6V5gqU4FbNINYgf3HrIeUadc7pMLH+NFu6wohVokCPd06DDSoEYFaUHi/0NKKl4tThfsERKcM5YBEcnBUglBpRCs9oY7Vaty9DjjD309LMSLD4UWN9phJOTFnYt7uLYi6djzTKY0V+mQvcG", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [BU = _t, Disposables = _t]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"BU", Int64.Type}, {"Disposables", type text}})
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

